name: Selenium Template
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  selenium:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: 'Create env file'
      run: |
        touch .env
        echo BROWSER=CHROME >> .env
        echo HEADLESS=true >> .env
        cat .env
    - name: Run Selenium tests
      run: node example.mjs
  lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install eslint
    - name: Lint
      run: npx eslint --max-warnings=0
